import type { NextPage } from "next";
import Head from "next/head";
import { Test } from "../src/components/Test";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS + Socket IO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Test />
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  );
};

export default Home;
